framework:
    default_locale: '%locale%'
    translator:
        fallbacks:
            - 'en'
                
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                domains: ['messages']
                locales: ['en', 'nl', 'es'] 
                
        enabled_locales: ['en', 'nl', 'es']

# php_translation
translation:
    webui:
        enabled: true
    edit_in_place:
        enabled: false
    configs:
        bolt:
            dirs: ["%kernel.project_dir%/templates", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
